/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AuthorizeNet.Rest.Model
{
    /// <summary>
    /// Model for CreditRequest
    /// </summary>
    [DataContract]
    public partial class CreditRequest :  IEquatable<CreditRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreditRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreditRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreditRequest" /> class.
        /// </summary>
        /// <param name="AmountDetail">AmountDetail (required).</param>
        /// <param name="PaymentInstrument">PaymentInstrument (required).</param>
        public CreditRequest(AmountDetail AmountDetail = null, PaymentInstrument PaymentInstrument = null)
        {
            // to ensure "AmountDetail" is required (not null)
            if (AmountDetail == null)
            {
                throw new InvalidDataException("AmountDetail is a required property for CreditRequest and cannot be null");
            }
            else
            {
                this.AmountDetail = AmountDetail;
            }
            // to ensure "PaymentInstrument" is required (not null)
            if (PaymentInstrument == null)
            {
                throw new InvalidDataException("PaymentInstrument is a required property for CreditRequest and cannot be null");
            }
            else
            {
                this.PaymentInstrument = PaymentInstrument;
            }
        }
        
        /// <summary>
        /// Gets or Sets AmountDetail
        /// </summary>
        [DataMember(Name="amountDetail", EmitDefaultValue=false)]
        public AmountDetail AmountDetail { get; set; }
        /// <summary>
        /// Gets or Sets PaymentInstrument
        /// </summary>
        [DataMember(Name="paymentInstrument", EmitDefaultValue=false)]
        public PaymentInstrument PaymentInstrument { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditRequest {\n");
            sb.Append("  AmountDetail: ").Append(AmountDetail).Append("\n");
            sb.Append("  PaymentInstrument: ").Append(PaymentInstrument).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreditRequest);
        }

        /// <summary>
        /// Returns true if CreditRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreditRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AmountDetail == other.AmountDetail ||
                    this.AmountDetail != null &&
                    this.AmountDetail.Equals(other.AmountDetail)
                ) && 
                (
                    this.PaymentInstrument == other.PaymentInstrument ||
                    this.PaymentInstrument != null &&
                    this.PaymentInstrument.Equals(other.PaymentInstrument)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AmountDetail != null)
                    hash = hash * 59 + this.AmountDetail.GetHashCode();
                if (this.PaymentInstrument != null)
                    hash = hash * 59 + this.PaymentInstrument.GetHashCode();
                return hash;
            }
        }
    }

}
