/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AuthorizeNet.Rest.Model
{
    /// <summary>
    /// InvoicesCollection
    /// </summary>
    [DataContract]
    public partial class InvoicesCollection :  IEquatable<InvoicesCollection>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvoicesCollection" /> class.
        /// </summary>
        /// <param name="Links">Links.</param>
        /// <param name="Embedded">Embedded.</param>
        /// <param name="TotalInvoices">TotalInvoices.</param>
        public InvoicesCollection(CollectionLinks Links = null, List<InvoiceListInfo> Embedded = null, int? TotalInvoices = null)
        {
            this.Links = Links;
            this.Embedded = Embedded;
            this.TotalInvoices = TotalInvoices;
        }
        
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="_links", EmitDefaultValue=false)]
        public CollectionLinks Links { get; set; }
        /// <summary>
        /// Gets or Sets Embedded
        /// </summary>
        [DataMember(Name="_embedded", EmitDefaultValue=false)]
        public List<InvoiceListInfo> Embedded { get; set; }
        /// <summary>
        /// Gets or Sets TotalInvoices
        /// </summary>
        [DataMember(Name="totalInvoices", EmitDefaultValue=false)]
        public int? TotalInvoices { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvoicesCollection {\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Embedded: ").Append(Embedded).Append("\n");
            sb.Append("  TotalInvoices: ").Append(TotalInvoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InvoicesCollection);
        }

        /// <summary>
        /// Returns true if InvoicesCollection instances are equal
        /// </summary>
        /// <param name="other">Instance of InvoicesCollection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvoicesCollection other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Links == other.Links ||
                    this.Links != null &&
                    this.Links.Equals(other.Links)
                ) && 
                (
                    this.Embedded == other.Embedded ||
                    this.Embedded != null &&
                    this.Embedded.SequenceEqual(other.Embedded)
                ) && 
                (
                    this.TotalInvoices == other.TotalInvoices ||
                    this.TotalInvoices != null &&
                    this.TotalInvoices.Equals(other.TotalInvoices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Links != null)
                    hash = hash * 59 + this.Links.GetHashCode();
                if (this.Embedded != null)
                    hash = hash * 59 + this.Embedded.GetHashCode();
                if (this.TotalInvoices != null)
                    hash = hash * 59 + this.TotalInvoices.GetHashCode();
                return hash;
            }
        }
    }

}
