/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using AuthorizeNet.Rest.Client;
using AuthorizeNet.Rest.Model;

namespace AuthorizeNet.Rest.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAddressesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create A Customer Address
        /// </summary>
        /// <remarks>
        /// Create A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Address</returns>
        Address CreateCustomerAddress (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null);

        /// <summary>
        /// Create A Customer Address
        /// </summary>
        /// <remarks>
        /// Create A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        ApiResponse<Address> CreateCustomerAddressWithHttpInfo (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null);
        /// <summary>
        /// Delete Address
        /// </summary>
        /// <remarks>
        /// Deletes a Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns></returns>
        void DeleteAddress (string customerId, string addressId, string authorization = null);

        /// <summary>
        /// Delete Address
        /// </summary>
        /// <remarks>
        /// Deletes a Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteAddressWithHttpInfo (string customerId, string addressId, string authorization = null);
        /// <summary>
        /// Get All Customer Addresses
        /// </summary>
        /// <remarks>
        /// Get All Customer Addresses
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>AddressCollection</returns>
        AddressCollection GetAllCustomerAddresses (string customerId, string authorization = null);

        /// <summary>
        /// Get All Customer Addresses
        /// </summary>
        /// <remarks>
        /// Get All Customer Addresses
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of AddressCollection</returns>
        ApiResponse<AddressCollection> GetAllCustomerAddressesWithHttpInfo (string customerId, string authorization = null);
        /// <summary>
        /// Get A Customer Address
        /// </summary>
        /// <remarks>
        /// Get A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Address</returns>
        Address GetCustomerAddress (string customerId, string addressId, string authorization = null);

        /// <summary>
        /// Get A Customer Address
        /// </summary>
        /// <remarks>
        /// Get A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        ApiResponse<Address> GetCustomerAddressWithHttpInfo (string customerId, string addressId, string authorization = null);
        /// <summary>
        /// Update A Customer Address
        /// </summary>
        /// <remarks>
        /// Update A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Address</returns>
        Address UpdateCustomerAddress (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null);

        /// <summary>
        /// Update A Customer Address
        /// </summary>
        /// <remarks>
        /// Update A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        ApiResponse<Address> UpdateCustomerAddressWithHttpInfo (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create A Customer Address
        /// </summary>
        /// <remarks>
        /// Create A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Address</returns>
        System.Threading.Tasks.Task<Address> CreateCustomerAddressAsync (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null);

        /// <summary>
        /// Create A Customer Address
        /// </summary>
        /// <remarks>
        /// Create A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        System.Threading.Tasks.Task<ApiResponse<Address>> CreateCustomerAddressAsyncWithHttpInfo (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null);
        /// <summary>
        /// Delete Address
        /// </summary>
        /// <remarks>
        /// Deletes a Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteAddressAsync (string customerId, string addressId, string authorization = null);

        /// <summary>
        /// Delete Address
        /// </summary>
        /// <remarks>
        /// Deletes a Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAddressAsyncWithHttpInfo (string customerId, string addressId, string authorization = null);
        /// <summary>
        /// Get All Customer Addresses
        /// </summary>
        /// <remarks>
        /// Get All Customer Addresses
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of AddressCollection</returns>
        System.Threading.Tasks.Task<AddressCollection> GetAllCustomerAddressesAsync (string customerId, string authorization = null);

        /// <summary>
        /// Get All Customer Addresses
        /// </summary>
        /// <remarks>
        /// Get All Customer Addresses
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (AddressCollection)</returns>
        System.Threading.Tasks.Task<ApiResponse<AddressCollection>> GetAllCustomerAddressesAsyncWithHttpInfo (string customerId, string authorization = null);
        /// <summary>
        /// Get A Customer Address
        /// </summary>
        /// <remarks>
        /// Get A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Address</returns>
        System.Threading.Tasks.Task<Address> GetCustomerAddressAsync (string customerId, string addressId, string authorization = null);

        /// <summary>
        /// Get A Customer Address
        /// </summary>
        /// <remarks>
        /// Get A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        System.Threading.Tasks.Task<ApiResponse<Address>> GetCustomerAddressAsyncWithHttpInfo (string customerId, string addressId, string authorization = null);
        /// <summary>
        /// Update A Customer Address
        /// </summary>
        /// <remarks>
        /// Update A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Address</returns>
        System.Threading.Tasks.Task<Address> UpdateCustomerAddressAsync (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null);

        /// <summary>
        /// Update A Customer Address
        /// </summary>
        /// <remarks>
        /// Update A Customer Address
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        System.Threading.Tasks.Task<ApiResponse<Address>> UpdateCustomerAddressAsyncWithHttpInfo (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AddressesApi : IAddressesApi
    {
        private AuthorizeNet.Rest.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AddressesApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = AuthorizeNet.Rest.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AddressesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AuthorizeNet.Rest.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AuthorizeNet.Rest.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create A Customer Address Create A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Address</returns>
        public Address CreateCustomerAddress (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
             ApiResponse<Address> localVarResponse = CreateCustomerAddressWithHttpInfo(customerId, createCustomerAddress, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A Customer Address Create A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        public ApiResponse< Address > CreateCustomerAddressWithHttpInfo (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->CreateCustomerAddress");
            // verify the required parameter 'createCustomerAddress' is set
            if (createCustomerAddress == null)
                throw new ApiException(400, "Missing required parameter 'createCustomerAddress' when calling AddressesApi->CreateCustomerAddress");

            var localVarPath = "/customers/{customerId}/addresses";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (createCustomerAddress != null && createCustomerAddress.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(createCustomerAddress); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createCustomerAddress; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateCustomerAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Address>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Address) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Address)));
            
        }

        /// <summary>
        /// Create A Customer Address Create A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Address</returns>
        public async System.Threading.Tasks.Task<Address> CreateCustomerAddressAsync (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
             ApiResponse<Address> localVarResponse = await CreateCustomerAddressAsyncWithHttpInfo(customerId, createCustomerAddress, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A Customer Address Create A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="createCustomerAddress">the \&quot;CreateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Address>> CreateCustomerAddressAsyncWithHttpInfo (string customerId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->CreateCustomerAddress");
            // verify the required parameter 'createCustomerAddress' is set
            if (createCustomerAddress == null)
                throw new ApiException(400, "Missing required parameter 'createCustomerAddress' when calling AddressesApi->CreateCustomerAddress");

            var localVarPath = "/customers/{customerId}/addresses";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (createCustomerAddress != null && createCustomerAddress.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(createCustomerAddress); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createCustomerAddress; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateCustomerAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Address>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Address) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Address)));
            
        }

        /// <summary>
        /// Delete Address Deletes a Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns></returns>
        public void DeleteAddress (string customerId, string addressId, string authorization = null)
        {
             DeleteAddressWithHttpInfo(customerId, addressId, authorization);
        }

        /// <summary>
        /// Delete Address Deletes a Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteAddressWithHttpInfo (string customerId, string addressId, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->DeleteAddress");
            // verify the required parameter 'addressId' is set
            if (addressId == null)
                throw new ApiException(400, "Missing required parameter 'addressId' when calling AddressesApi->DeleteAddress");

            var localVarPath = "/customers/{customerId}/addresses/{addressId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (addressId != null) localVarPathParams.Add("addressId", Configuration.ApiClient.ParameterToString(addressId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete Address Deletes a Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteAddressAsync (string customerId, string addressId, string authorization = null)
        {
             await DeleteAddressAsyncWithHttpInfo(customerId, addressId, authorization);

        }

        /// <summary>
        /// Delete Address Deletes a Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAddressAsyncWithHttpInfo (string customerId, string addressId, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->DeleteAddress");
            // verify the required parameter 'addressId' is set
            if (addressId == null)
                throw new ApiException(400, "Missing required parameter 'addressId' when calling AddressesApi->DeleteAddress");

            var localVarPath = "/customers/{customerId}/addresses/{addressId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (addressId != null) localVarPathParams.Add("addressId", Configuration.ApiClient.ParameterToString(addressId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get All Customer Addresses Get All Customer Addresses
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>AddressCollection</returns>
        public AddressCollection GetAllCustomerAddresses (string customerId, string authorization = null)
        {
             ApiResponse<AddressCollection> localVarResponse = GetAllCustomerAddressesWithHttpInfo(customerId, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get All Customer Addresses Get All Customer Addresses
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of AddressCollection</returns>
        public ApiResponse< AddressCollection > GetAllCustomerAddressesWithHttpInfo (string customerId, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->GetAllCustomerAddresses");

            var localVarPath = "/customers/{customerId}/addresses";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllCustomerAddresses", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AddressCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AddressCollection) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AddressCollection)));
            
        }

        /// <summary>
        /// Get All Customer Addresses Get All Customer Addresses
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of AddressCollection</returns>
        public async System.Threading.Tasks.Task<AddressCollection> GetAllCustomerAddressesAsync (string customerId, string authorization = null)
        {
             ApiResponse<AddressCollection> localVarResponse = await GetAllCustomerAddressesAsyncWithHttpInfo(customerId, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get All Customer Addresses Get All Customer Addresses
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (AddressCollection)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AddressCollection>> GetAllCustomerAddressesAsyncWithHttpInfo (string customerId, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->GetAllCustomerAddresses");

            var localVarPath = "/customers/{customerId}/addresses";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllCustomerAddresses", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AddressCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AddressCollection) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AddressCollection)));
            
        }

        /// <summary>
        /// Get A Customer Address Get A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Address</returns>
        public Address GetCustomerAddress (string customerId, string addressId, string authorization = null)
        {
             ApiResponse<Address> localVarResponse = GetCustomerAddressWithHttpInfo(customerId, addressId, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get A Customer Address Get A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        public ApiResponse< Address > GetCustomerAddressWithHttpInfo (string customerId, string addressId, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->GetCustomerAddress");
            // verify the required parameter 'addressId' is set
            if (addressId == null)
                throw new ApiException(400, "Missing required parameter 'addressId' when calling AddressesApi->GetCustomerAddress");

            var localVarPath = "/customers/{customerId}/addresses/{addressId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (addressId != null) localVarPathParams.Add("addressId", Configuration.ApiClient.ParameterToString(addressId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomerAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Address>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Address) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Address)));
            
        }

        /// <summary>
        /// Get A Customer Address Get A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Address</returns>
        public async System.Threading.Tasks.Task<Address> GetCustomerAddressAsync (string customerId, string addressId, string authorization = null)
        {
             ApiResponse<Address> localVarResponse = await GetCustomerAddressAsyncWithHttpInfo(customerId, addressId, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get A Customer Address Get A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">Address ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Address>> GetCustomerAddressAsyncWithHttpInfo (string customerId, string addressId, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->GetCustomerAddress");
            // verify the required parameter 'addressId' is set
            if (addressId == null)
                throw new ApiException(400, "Missing required parameter 'addressId' when calling AddressesApi->GetCustomerAddress");

            var localVarPath = "/customers/{customerId}/addresses/{addressId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (addressId != null) localVarPathParams.Add("addressId", Configuration.ApiClient.ParameterToString(addressId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomerAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Address>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Address) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Address)));
            
        }

        /// <summary>
        /// Update A Customer Address Update A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Address</returns>
        public Address UpdateCustomerAddress (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
             ApiResponse<Address> localVarResponse = UpdateCustomerAddressWithHttpInfo(customerId, addressId, createCustomerAddress, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update A Customer Address Update A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        public ApiResponse< Address > UpdateCustomerAddressWithHttpInfo (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->UpdateCustomerAddress");
            // verify the required parameter 'addressId' is set
            if (addressId == null)
                throw new ApiException(400, "Missing required parameter 'addressId' when calling AddressesApi->UpdateCustomerAddress");
            // verify the required parameter 'createCustomerAddress' is set
            if (createCustomerAddress == null)
                throw new ApiException(400, "Missing required parameter 'createCustomerAddress' when calling AddressesApi->UpdateCustomerAddress");

            var localVarPath = "/customers/{customerId}/addresses/{addressId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (addressId != null) localVarPathParams.Add("addressId", Configuration.ApiClient.ParameterToString(addressId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (createCustomerAddress != null && createCustomerAddress.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(createCustomerAddress); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createCustomerAddress; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateCustomerAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Address>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Address) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Address)));
            
        }

        /// <summary>
        /// Update A Customer Address Update A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Address</returns>
        public async System.Threading.Tasks.Task<Address> UpdateCustomerAddressAsync (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
             ApiResponse<Address> localVarResponse = await UpdateCustomerAddressAsyncWithHttpInfo(customerId, addressId, createCustomerAddress, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update A Customer Address Update A Customer Address
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID</param>
        /// <param name="addressId">address  ID</param>
        /// <param name="createCustomerAddress">the \&quot;UpdateCustomerAddress\&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Address>> UpdateCustomerAddressAsyncWithHttpInfo (string customerId, string addressId, CreateCustomerAddress createCustomerAddress, string authorization = null)
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new ApiException(400, "Missing required parameter 'customerId' when calling AddressesApi->UpdateCustomerAddress");
            // verify the required parameter 'addressId' is set
            if (addressId == null)
                throw new ApiException(400, "Missing required parameter 'addressId' when calling AddressesApi->UpdateCustomerAddress");
            // verify the required parameter 'createCustomerAddress' is set
            if (createCustomerAddress == null)
                throw new ApiException(400, "Missing required parameter 'createCustomerAddress' when calling AddressesApi->UpdateCustomerAddress");

            var localVarPath = "/customers/{customerId}/addresses/{addressId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (customerId != null) localVarPathParams.Add("customerId", Configuration.ApiClient.ParameterToString(customerId)); // path parameter
            if (addressId != null) localVarPathParams.Add("addressId", Configuration.ApiClient.ParameterToString(addressId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (createCustomerAddress != null && createCustomerAddress.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(createCustomerAddress); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createCustomerAddress; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateCustomerAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Address>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Address) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Address)));
            
        }

    }
}
