/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using AuthorizeNet.Rest.Client;
using AuthorizeNet.Rest.Model;

namespace AuthorizeNet.Rest.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInvoicesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Invoice API
        /// </summary>
        /// <remarks>
        /// ANet API for creating new invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        Invoice CreateInvoice (CreateInvoice createInvoice, string authorization = null);

        /// <summary>
        /// Create Invoice API
        /// </summary>
        /// <remarks>
        /// ANet API for creating new invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        ApiResponse<Invoice> CreateInvoiceWithHttpInfo (CreateInvoice createInvoice, string authorization = null);
        /// <summary>
        /// Get List of Invoices
        /// </summary>
        /// <remarks>
        /// ANet API for getting list of invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>InvoicesCollection</returns>
        InvoicesCollection GetAllInvoices (int? offset, int? limit, string authorization = null);

        /// <summary>
        /// Get List of Invoices
        /// </summary>
        /// <remarks>
        /// ANet API for getting list of invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of InvoicesCollection</returns>
        ApiResponse<InvoicesCollection> GetAllInvoicesWithHttpInfo (int? offset, int? limit, string authorization = null);
        /// <summary>
        /// Get Invoice Details
        /// </summary>
        /// <remarks>
        /// ANet API to get invoice details
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        Invoice GetInvoice (string invoiceNumber, string authorization = null);

        /// <summary>
        /// Get Invoice Details
        /// </summary>
        /// <remarks>
        /// ANet API to get invoice details
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        ApiResponse<Invoice> GetInvoiceWithHttpInfo (string invoiceNumber, string authorization = null);
        /// <summary>
        /// Perform an action on Invoice
        /// </summary>
        /// <remarks>
        /// ANet API to Perform an action on Invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        Invoice PerformActions (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null);

        /// <summary>
        /// Perform an action on Invoice
        /// </summary>
        /// <remarks>
        /// ANet API to Perform an action on Invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        ApiResponse<Invoice> PerformActionsWithHttpInfo (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null);
        /// <summary>
        /// Update Invoice API
        /// </summary>
        /// <remarks>
        /// ANet APIs for editing an invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        Invoice UpdateInvoice (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null);

        /// <summary>
        /// Update Invoice API
        /// </summary>
        /// <remarks>
        /// ANet APIs for editing an invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        ApiResponse<Invoice> UpdateInvoiceWithHttpInfo (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create Invoice API
        /// </summary>
        /// <remarks>
        /// ANet API for creating new invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        System.Threading.Tasks.Task<Invoice> CreateInvoiceAsync (CreateInvoice createInvoice, string authorization = null);

        /// <summary>
        /// Create Invoice API
        /// </summary>
        /// <remarks>
        /// ANet API for creating new invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        System.Threading.Tasks.Task<ApiResponse<Invoice>> CreateInvoiceAsyncWithHttpInfo (CreateInvoice createInvoice, string authorization = null);
        /// <summary>
        /// Get List of Invoices
        /// </summary>
        /// <remarks>
        /// ANet API for getting list of invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of InvoicesCollection</returns>
        System.Threading.Tasks.Task<InvoicesCollection> GetAllInvoicesAsync (int? offset, int? limit, string authorization = null);

        /// <summary>
        /// Get List of Invoices
        /// </summary>
        /// <remarks>
        /// ANet API for getting list of invoices
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (InvoicesCollection)</returns>
        System.Threading.Tasks.Task<ApiResponse<InvoicesCollection>> GetAllInvoicesAsyncWithHttpInfo (int? offset, int? limit, string authorization = null);
        /// <summary>
        /// Get Invoice Details
        /// </summary>
        /// <remarks>
        /// ANet API to get invoice details
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        System.Threading.Tasks.Task<Invoice> GetInvoiceAsync (string invoiceNumber, string authorization = null);

        /// <summary>
        /// Get Invoice Details
        /// </summary>
        /// <remarks>
        /// ANet API to get invoice details
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        System.Threading.Tasks.Task<ApiResponse<Invoice>> GetInvoiceAsyncWithHttpInfo (string invoiceNumber, string authorization = null);
        /// <summary>
        /// Perform an action on Invoice
        /// </summary>
        /// <remarks>
        /// ANet API to Perform an action on Invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        System.Threading.Tasks.Task<Invoice> PerformActionsAsync (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null);

        /// <summary>
        /// Perform an action on Invoice
        /// </summary>
        /// <remarks>
        /// ANet API to Perform an action on Invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        System.Threading.Tasks.Task<ApiResponse<Invoice>> PerformActionsAsyncWithHttpInfo (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null);
        /// <summary>
        /// Update Invoice API
        /// </summary>
        /// <remarks>
        /// ANet APIs for editing an invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        System.Threading.Tasks.Task<Invoice> UpdateInvoiceAsync (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null);

        /// <summary>
        /// Update Invoice API
        /// </summary>
        /// <remarks>
        /// ANet APIs for editing an invoice
        /// </remarks>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        System.Threading.Tasks.Task<ApiResponse<Invoice>> UpdateInvoiceAsyncWithHttpInfo (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class InvoicesApi : IInvoicesApi
    {
        private AuthorizeNet.Rest.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoicesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public InvoicesApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = AuthorizeNet.Rest.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoicesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public InvoicesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AuthorizeNet.Rest.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AuthorizeNet.Rest.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create Invoice API ANet API for creating new invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        public Invoice CreateInvoice (CreateInvoice createInvoice, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = CreateInvoiceWithHttpInfo(createInvoice, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create Invoice API ANet API for creating new invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        public ApiResponse< Invoice > CreateInvoiceWithHttpInfo (CreateInvoice createInvoice, string authorization = null)
        {
            // verify the required parameter 'createInvoice' is set
            if (createInvoice == null)
                throw new ApiException(400, "Missing required parameter 'createInvoice' when calling InvoicesApi->CreateInvoice");

            var localVarPath = "/invoices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (createInvoice != null && createInvoice.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(createInvoice); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createInvoice; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateInvoice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Create Invoice API ANet API for creating new invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        public async System.Threading.Tasks.Task<Invoice> CreateInvoiceAsync (CreateInvoice createInvoice, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = await CreateInvoiceAsyncWithHttpInfo(createInvoice, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create Invoice API ANet API for creating new invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createInvoice">The \&quot;create invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Invoice>> CreateInvoiceAsyncWithHttpInfo (CreateInvoice createInvoice, string authorization = null)
        {
            // verify the required parameter 'createInvoice' is set
            if (createInvoice == null)
                throw new ApiException(400, "Missing required parameter 'createInvoice' when calling InvoicesApi->CreateInvoice");

            var localVarPath = "/invoices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (createInvoice != null && createInvoice.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(createInvoice); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createInvoice; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateInvoice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Get List of Invoices ANet API for getting list of invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>InvoicesCollection</returns>
        public InvoicesCollection GetAllInvoices (int? offset, int? limit, string authorization = null)
        {
             ApiResponse<InvoicesCollection> localVarResponse = GetAllInvoicesWithHttpInfo(offset, limit, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get List of Invoices ANet API for getting list of invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of InvoicesCollection</returns>
        public ApiResponse< InvoicesCollection > GetAllInvoicesWithHttpInfo (int? offset, int? limit, string authorization = null)
        {
            // verify the required parameter 'offset' is set
            if (offset == null)
                throw new ApiException(400, "Missing required parameter 'offset' when calling InvoicesApi->GetAllInvoices");
            // verify the required parameter 'limit' is set
            if (limit == null)
                throw new ApiException(400, "Missing required parameter 'limit' when calling InvoicesApi->GetAllInvoices");

            var localVarPath = "/invoices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllInvoices", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InvoicesCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InvoicesCollection) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InvoicesCollection)));
            
        }

        /// <summary>
        /// Get List of Invoices ANet API for getting list of invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of InvoicesCollection</returns>
        public async System.Threading.Tasks.Task<InvoicesCollection> GetAllInvoicesAsync (int? offset, int? limit, string authorization = null)
        {
             ApiResponse<InvoicesCollection> localVarResponse = await GetAllInvoicesAsyncWithHttpInfo(offset, limit, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get List of Invoices ANet API for getting list of invoices
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">Page offset number</param>
        /// <param name="limit">Number of items to be returned</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (InvoicesCollection)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InvoicesCollection>> GetAllInvoicesAsyncWithHttpInfo (int? offset, int? limit, string authorization = null)
        {
            // verify the required parameter 'offset' is set
            if (offset == null)
                throw new ApiException(400, "Missing required parameter 'offset' when calling InvoicesApi->GetAllInvoices");
            // verify the required parameter 'limit' is set
            if (limit == null)
                throw new ApiException(400, "Missing required parameter 'limit' when calling InvoicesApi->GetAllInvoices");

            var localVarPath = "/invoices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllInvoices", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InvoicesCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InvoicesCollection) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InvoicesCollection)));
            
        }

        /// <summary>
        /// Get Invoice Details ANet API to get invoice details
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        public Invoice GetInvoice (string invoiceNumber, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = GetInvoiceWithHttpInfo(invoiceNumber, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Invoice Details ANet API to get invoice details
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        public ApiResponse< Invoice > GetInvoiceWithHttpInfo (string invoiceNumber, string authorization = null)
        {
            // verify the required parameter 'invoiceNumber' is set
            if (invoiceNumber == null)
                throw new ApiException(400, "Missing required parameter 'invoiceNumber' when calling InvoicesApi->GetInvoice");

            var localVarPath = "/invoices/{invoiceNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (invoiceNumber != null) localVarPathParams.Add("invoiceNumber", Configuration.ApiClient.ParameterToString(invoiceNumber)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetInvoice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Get Invoice Details ANet API to get invoice details
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        public async System.Threading.Tasks.Task<Invoice> GetInvoiceAsync (string invoiceNumber, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = await GetInvoiceAsyncWithHttpInfo(invoiceNumber, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Invoice Details ANet API to get invoice details
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Invoice>> GetInvoiceAsyncWithHttpInfo (string invoiceNumber, string authorization = null)
        {
            // verify the required parameter 'invoiceNumber' is set
            if (invoiceNumber == null)
                throw new ApiException(400, "Missing required parameter 'invoiceNumber' when calling InvoicesApi->GetInvoice");

            var localVarPath = "/invoices/{invoiceNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (invoiceNumber != null) localVarPathParams.Add("invoiceNumber", Configuration.ApiClient.ParameterToString(invoiceNumber)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetInvoice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Perform an action on Invoice ANet API to Perform an action on Invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        public Invoice PerformActions (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = PerformActionsWithHttpInfo(invoiceNumber, invoiceAction, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform an action on Invoice ANet API to Perform an action on Invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        public ApiResponse< Invoice > PerformActionsWithHttpInfo (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null)
        {
            // verify the required parameter 'invoiceNumber' is set
            if (invoiceNumber == null)
                throw new ApiException(400, "Missing required parameter 'invoiceNumber' when calling InvoicesApi->PerformActions");
            // verify the required parameter 'invoiceAction' is set
            if (invoiceAction == null)
                throw new ApiException(400, "Missing required parameter 'invoiceAction' when calling InvoicesApi->PerformActions");

            var localVarPath = "/invoices/{invoiceNumber}/actions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (invoiceNumber != null) localVarPathParams.Add("invoiceNumber", Configuration.ApiClient.ParameterToString(invoiceNumber)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (invoiceAction != null && invoiceAction.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(invoiceAction); // http body (model) parameter
            }
            else
            {
                localVarPostBody = invoiceAction; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PerformActions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Perform an action on Invoice ANet API to Perform an action on Invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        public async System.Threading.Tasks.Task<Invoice> PerformActionsAsync (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = await PerformActionsAsyncWithHttpInfo(invoiceNumber, invoiceAction, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform an action on Invoice ANet API to Perform an action on Invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="invoiceAction">Perform an action on invoice</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Invoice>> PerformActionsAsyncWithHttpInfo (string invoiceNumber, InvoiceAction invoiceAction, string authorization = null)
        {
            // verify the required parameter 'invoiceNumber' is set
            if (invoiceNumber == null)
                throw new ApiException(400, "Missing required parameter 'invoiceNumber' when calling InvoicesApi->PerformActions");
            // verify the required parameter 'invoiceAction' is set
            if (invoiceAction == null)
                throw new ApiException(400, "Missing required parameter 'invoiceAction' when calling InvoicesApi->PerformActions");

            var localVarPath = "/invoices/{invoiceNumber}/actions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (invoiceNumber != null) localVarPathParams.Add("invoiceNumber", Configuration.ApiClient.ParameterToString(invoiceNumber)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (invoiceAction != null && invoiceAction.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(invoiceAction); // http body (model) parameter
            }
            else
            {
                localVarPostBody = invoiceAction; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PerformActions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Update Invoice API ANet APIs for editing an invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Invoice</returns>
        public Invoice UpdateInvoice (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = UpdateInvoiceWithHttpInfo(invoiceNumber, updateInvoice, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update Invoice API ANet APIs for editing an invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        public ApiResponse< Invoice > UpdateInvoiceWithHttpInfo (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null)
        {
            // verify the required parameter 'invoiceNumber' is set
            if (invoiceNumber == null)
                throw new ApiException(400, "Missing required parameter 'invoiceNumber' when calling InvoicesApi->UpdateInvoice");
            // verify the required parameter 'updateInvoice' is set
            if (updateInvoice == null)
                throw new ApiException(400, "Missing required parameter 'updateInvoice' when calling InvoicesApi->UpdateInvoice");

            var localVarPath = "/invoices/{invoiceNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (invoiceNumber != null) localVarPathParams.Add("invoiceNumber", Configuration.ApiClient.ParameterToString(invoiceNumber)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (updateInvoice != null && updateInvoice.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(updateInvoice); // http body (model) parameter
            }
            else
            {
                localVarPostBody = updateInvoice; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateInvoice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

        /// <summary>
        /// Update Invoice API ANet APIs for editing an invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of Invoice</returns>
        public async System.Threading.Tasks.Task<Invoice> UpdateInvoiceAsync (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null)
        {
             ApiResponse<Invoice> localVarResponse = await UpdateInvoiceAsyncWithHttpInfo(invoiceNumber, updateInvoice, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update Invoice API ANet APIs for editing an invoice
        /// </summary>
        /// <exception cref="AuthorizeNet.Rest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="invoiceNumber">Invoice ID</param>
        /// <param name="updateInvoice">The \&quot;update invoice \&quot; model</param>
        /// <param name="authorization">The value to provide in the Authorization header of ANET API request (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Invoice>> UpdateInvoiceAsyncWithHttpInfo (string invoiceNumber, UpdateInvoice updateInvoice, string authorization = null)
        {
            // verify the required parameter 'invoiceNumber' is set
            if (invoiceNumber == null)
                throw new ApiException(400, "Missing required parameter 'invoiceNumber' when calling InvoicesApi->UpdateInvoice");
            // verify the required parameter 'updateInvoice' is set
            if (updateInvoice == null)
                throw new ApiException(400, "Missing required parameter 'updateInvoice' when calling InvoicesApi->UpdateInvoice");

            var localVarPath = "/invoices/{invoiceNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (invoiceNumber != null) localVarPathParams.Add("invoiceNumber", Configuration.ApiClient.ParameterToString(invoiceNumber)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (updateInvoice != null && updateInvoice.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(updateInvoice); // http body (model) parameter
            }
            else
            {
                localVarPostBody = updateInvoice; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateInvoice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Invoice>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Invoice) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Invoice)));
            
        }

    }
}
