/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AuthorizeNet.Rest.Api;
using AuthorizeNet.Rest.Model;
using AuthorizeNet.Rest.Client;
using System.Reflection;

namespace AuthorizeNet.Rest.Test
{
    /// <summary>
    ///  Class for testing CreateCustomerAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCustomerAddressTests
    {
        // TODO uncomment below to declare an instance variable for CreateCustomerAddress
        //private CreateCustomerAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCustomerAddress
            //instance = new CreateCustomerAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCustomerAddress
        /// </summary>
        [Test]
        public void CreateCustomerAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateCustomerAddress
            //Assert.IsInstanceOf<CreateCustomerAddress> (instance, "variable 'instance' is a CreateCustomerAddress");
        }

        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'AdministrativeArea'
        /// </summary>
        [Test]
        public void AdministrativeAreaTest()
        {
            // TODO unit test for the property 'AdministrativeArea'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Locality'
        /// </summary>
        [Test]
        public void LocalityTest()
        {
            // TODO unit test for the property 'Locality'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

    }

}
