/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AuthorizeNet.Rest.Api;
using AuthorizeNet.Rest.Model;
using AuthorizeNet.Rest.Client;
using System.Reflection;

namespace AuthorizeNet.Rest.Test
{
    /// <summary>
    ///  Class for testing Notification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationTests
    {
        // TODO uncomment below to declare an instance variable for Notification
        //private Notification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Notification
            //instance = new Notification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Notification
        /// </summary>
        [Test]
        public void NotificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Notification
            //Assert.IsInstanceOfType<Notification> (instance, "variable 'instance' is a Notification");
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'NotificationId'
        /// </summary>
        [Test]
        public void NotificationIdTest()
        {
            // TODO unit test for the property 'NotificationId'
        }
        /// <summary>
        /// Test the property 'DeliveryStatus'
        /// </summary>
        [Test]
        public void DeliveryStatusTest()
        {
            // TODO unit test for the property 'DeliveryStatus'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Test]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Test]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'WebhookId'
        /// </summary>
        [Test]
        public void WebhookIdTest()
        {
            // TODO unit test for the property 'WebhookId'
        }

    }

}
