/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AuthorizeNet.Rest.Api;
using AuthorizeNet.Rest.Model;
using AuthorizeNet.Rest.Client;
using System.Reflection;

namespace AuthorizeNet.Rest.Test
{
    /// <summary>
    ///  Class for testing PaymentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentRequestTests
    {
        // TODO uncomment below to declare an instance variable for PaymentRequest
        //private PaymentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentRequest
            //instance = new PaymentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentRequest
        /// </summary>
        [Test]
        public void PaymentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentRequest
            //Assert.IsInstanceOfType<PaymentRequest> (instance, "variable 'instance' is a PaymentRequest");
        }

        /// <summary>
        /// Test the property 'Capture'
        /// </summary>
        [Test]
        public void CaptureTest()
        {
            // TODO unit test for the property 'Capture'
        }
        /// <summary>
        /// Test the property 'AmountDetail'
        /// </summary>
        [Test]
        public void AmountDetailTest()
        {
            // TODO unit test for the property 'AmountDetail'
        }
        /// <summary>
        /// Test the property 'Solution'
        /// </summary>
        [Test]
        public void SolutionTest()
        {
            // TODO unit test for the property 'Solution'
        }
        /// <summary>
        /// Test the property 'PaymentInstrument'
        /// </summary>
        [Test]
        public void PaymentInstrumentTest()
        {
            // TODO unit test for the property 'PaymentInstrument'
        }
        /// <summary>
        /// Test the property 'BillTo'
        /// </summary>
        [Test]
        public void BillToTest()
        {
            // TODO unit test for the property 'BillTo'
        }
        /// <summary>
        /// Test the property 'ShipTo'
        /// </summary>
        [Test]
        public void ShipToTest()
        {
            // TODO unit test for the property 'ShipTo'
        }
        /// <summary>
        /// Test the property 'CustomerIp'
        /// </summary>
        [Test]
        public void CustomerIpTest()
        {
            // TODO unit test for the property 'CustomerIp'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'Duty'
        /// </summary>
        [Test]
        public void DutyTest()
        {
            // TODO unit test for the property 'Duty'
        }
        /// <summary>
        /// Test the property 'Shipping'
        /// </summary>
        [Test]
        public void ShippingTest()
        {
            // TODO unit test for the property 'Shipping'
        }
        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Test]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }

    }

}
