/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AuthorizeNet.Rest.Api;
using AuthorizeNet.Rest.Model;
using AuthorizeNet.Rest.Client;
using System.Reflection;

namespace AuthorizeNet.Rest.Test
{
    /// <summary>
    ///  Class for testing UpdateInvoice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateInvoiceTests
    {
        // TODO uncomment below to declare an instance variable for UpdateInvoice
        //private UpdateInvoice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateInvoice
            //instance = new UpdateInvoice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateInvoice
        /// </summary>
        [Test]
        public void UpdateInvoiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateInvoice
            //Assert.IsInstanceOfType<UpdateInvoice> (instance, "variable 'instance' is a UpdateInvoice");
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'PayerName'
        /// </summary>
        [Test]
        public void PayerNameTest()
        {
            // TODO unit test for the property 'PayerName'
        }
        /// <summary>
        /// Test the property 'PaymentDueDate'
        /// </summary>
        [Test]
        public void PaymentDueDateTest()
        {
            // TODO unit test for the property 'PaymentDueDate'
        }
        /// <summary>
        /// Test the property 'SubAmount'
        /// </summary>
        [Test]
        public void SubAmountTest()
        {
            // TODO unit test for the property 'SubAmount'
        }
        /// <summary>
        /// Test the property 'DiscountPercent'
        /// </summary>
        [Test]
        public void DiscountPercentTest()
        {
            // TODO unit test for the property 'DiscountPercent'
        }
        /// <summary>
        /// Test the property 'DiscountAmount'
        /// </summary>
        [Test]
        public void DiscountAmountTest()
        {
            // TODO unit test for the property 'DiscountAmount'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Test]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Test]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }

    }

}
