/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AuthorizeNet.Rest.Client;
using AuthorizeNet.Rest.Api;
using AuthorizeNet.Rest.Model;

namespace AuthorizeNet.Rest.Test
{
    /// <summary>
    ///  Class for testing ForcedCapturesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ForcedCapturesApiTests
    {
        private ForcedCapturesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ForcedCapturesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForcedCapturesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // test 'IsInstanceOfType' ForcedCapturesApi
            Assert.IsInstanceOfType(typeof(ForcedCapturesApi), instance, "instance is a ForcedCapturesApi");
        }

        
        /// <summary>
        /// Test CreateAForcedCapture
        /// </summary>
        [Test]
        public void CreateAForcedCaptureTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ForcedCaptureRequest body = null;
            //string authorization = null;
            //var response = instance.CreateAForcedCapture(body, authorization);
            //Assert.IsInstanceOf<Payment> (response, "response is Payment");
        }
        
    }

}
