/* 
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;
using NMock;

using AuthorizeNet.Rest.Client;
using AuthorizeNet.Rest.Api;
using AuthorizeNet.Rest.Model;
using System.Net;

namespace AuthorizeNet.Rest.Test
{
    /// <summary>
    ///  Class for testing RefundsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RefundsApiTests
    {
        private RefundsApi instance;

        private MockFactory mockFactory = new MockFactory();
        
        private Mock<IRestClient> mockRestClient;

        private RestResponse paymentResponse = null;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            mockRestClient = mockFactory.CreateMock<IRestClient>();
            mockRestClient.Expects.AtLeastOne.GetProperty(_ => _.Timeout).WillReturn(60000);
            mockRestClient.Expects.AtLeastOne.GetProperty(_ => _.UserAgent).WillReturn("asdasd");
            mockRestClient.Expects.AtLeastOne.SetPropertyTo(_ => _.Timeout = 60000);
            mockRestClient.Expects.AtLeastOne.SetPropertyTo(_ => _.UserAgent = "asdasd");

            paymentResponse = new RestResponse
            {
                StatusCode = HttpStatusCode.OK,
                Content = @"{ ""_links"": { ""self"": { ""href"": "" / rest / v1 / payments / 60036591146"", ""method"": ""GET"" },
                ""refund"": { ""href"": "" / rest / v1 / payments / 60036591146 / refunds"",      ""method"": ""POST""    }
                  },  ""id"": ""60036591146"",  ""submitTimeUTC"": ""12/22/2017 06:23:06"",  ""submitTimeLocal"": ""12/21/2017 22:23:06"",  ""transactionStatus"": ""declined"",  ""processor"": {    ""avsResponse"": ""P""  },  ""recurringBilling"": false,  ""customerIp"": ""10.142.12.19"",  ""order"": {    ""purchaseOrderNumber"": ""12365""  },  ""authAmount"": ""4000.00"",  ""settleAmount"": ""4000.00"",  ""lineItems"": [    {      ""itemId"": ""1"",      ""name"": ""tshir"",      ""description"": ""t-shir desc"",      ""quantity"": 1,      ""unitPrice"": ""100.00"",      ""taxable"": true    }  ],  ""taxExempt"": false,  ""paymentInstrument"": {    ""bankAccount"": {      ""accountType"": ""SA"",      ""routingNumber"": ""XXXX0760"",      ""accountNumber"": ""XXXX3342"",      ""nameOnAccount"": ""demo acount"",      ""eCheckType"": ""WEB""    }  },  ""billTo"": {    ""address1"": ""Demo Adress"",    ""company"": ""XXXXCOMAPNAY"",    ""country"": ""India"",    ""firstName"": ""Demo fst"",    ""lastName"": ""Demo Second"",    ""phoneNumber"": ""1123456987"",    ""postalCode"": ""192123""  },  ""shipTo"": {    ""address1"": ""Demo Adress"",    ""company"": ""XXXXCOMAPNAY"",    ""country"": ""India"",    ""firstName"": ""Demo"",    ""lastName"": ""Demo Second"",    ""phoneNumber"": ""1123456987"",    ""postalCode"": ""192123""  }}"
            };
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test CreateRefundAPayment
        /// </summary>
        [Test]
        public void CreateRefundAPaymentTest()
        {
            string paymentId = "40006143732";
            //Amount Details
            AmountDetail amountDetail = new AmountDetail("100.00", "USD");

            // Solution Details
            Solution solution = new Solution
            {
                Name = "SolDemo",
                VendorName = "VenodeName"
            };

            // Credit Card
            CreditCard creditCard = new CreditCard("1111", "XXXX", "VISA", "123");

            // Bank Account
            BankAccount bankAccount = new BankAccount(null, "325070760", "4111111", "demo acount", null, "bank anme",
                null);
            //Base AddressBillTo
            BaseAddress baseAdressBillTo = new BaseAddress
            {
                Address1 = " Demo Adress",
                Company = "XXXXCOMAPNAY",
                Country = "India",
                FirstName = "Demo first",
                LastName = "Demo Second",
                PhoneNumber = "1123456987",
                PostalCode = "192123"
            };

            //Base AddressShipTo
            BaseAddress baseAdressShipTo = new BaseAddress
            {
                Address1 = " Demo Adress",
                Company = "XXXXCOMAPNAY",
                Country = "India",
                FirstName = "Demo first",
                LastName = "Demo Second",
                PhoneNumber = "1123456987",
                PostalCode = "192123"
            };

            // Ip Address
            String Ip = null;

            // Order 
            Order order = new Order("12365");

            // Extended Amount Tax
            ExtendedAmount extendedAmountTax = new ExtendedAmount("100.00", "Tax", "Tax");

            // Extended Amount Duty
            ExtendedAmount extendedAmountDuty = new ExtendedAmount("100.00", "duty", "Duty");

            // Extended Amount Ship
            ExtendedAmount extendedAmountShip = new ExtendedAmount("100.00", "ship", "Ship");

            //Payment Instrunment 
            //  PaymentInstrument paymentInstrument = new PaymentInstrument(null, bankAccount, null, null, true);
            PaymentInstrument paymentInstrument = new PaymentInstrument(creditCard, null, null, null, true);

            List<LineItem> lineItems = new List<LineItem>();
            lineItems.Add(new LineItem("1", "tshir", "tshir desc", 1, "100", true));

            RefundRequest body = new RefundRequest("50.00", order, lineItems, extendedAmountTax, extendedAmountShip,
                extendedAmountDuty, paymentInstrument, baseAdressBillTo, baseAdressShipTo);
            string authorization = "Basic asdadsa";
            mockRestClient.Expects.One.Method(v => v.Execute(new RestRequest())).With(NMock.Is.TypeOf(typeof(RestRequest))).WillReturn(paymentResponse);
            ApiClient apiClient = new ApiClient(mockRestClient.MockObject);

            apiClient.Configuration = null;

            Configuration configuration = new Configuration
            {
                ApiClient = apiClient,
                Username = "Asdads",
                Password = "asdasd",
                AccessToken = null,
                ApiKey = null,
                ApiKeyPrefix = null,
                TempFolderPath = null,
                DateTimeFormat = null,
                Timeout = 60000,
                UserAgent = "asdasd"
            };

            instance = new RefundsApi(configuration);

            var response = instance.CreateRefundAPayment(paymentId, body, authorization);
            Assert.IsInstanceOf<Payment>(response, "response is Payment");
        }
    }
}
